-- Query查询结果默认限制200行，如需更多数据请修改limit，最多展示10000行或20M。
set hg_experimental_enable_shard_count_cap =off;
CALL HG_CREATE_TABLE_GROUP ('tg_120', 120);
CALL HG_UPDATE_DATABASE_PROPERTY ('default_table_group', 'tg_120');
DROP table if EXISTS hits;
CREATE TABLE hits
(
    WatchID BIGINT NOT NULL,
    JavaEnable int NOT NULL,
    Title TEXT NOT NULL,
    GoodEvent int NOT NULL,
    EventTime timestamptz NOT NULL,
    EventDate timestamptz NOT NULL,
    CounterID INTEGER NOT NULL,
    ClientIP INTEGER NOT NULL,
    RegionID INTEGER NOT NULL,
    UserID BIGINT NOT NULL,
    CounterClass int NOT NULL,
    OS int NOT NULL,
    UserAgent int NOT NULL,
    URL TEXT NOT NULL,
    Referer TEXT NOT NULL,
    IsRefresh int NOT NULL,
    RefererCategoryID int NOT NULL,
    RefererRegionID INTEGER NOT NULL,
    URLCategoryID int NOT NULL,
    URLRegionID INTEGER NOT NULL,
    ResolutionWidth int NOT NULL,
    ResolutionHeight int NOT NULL,
    ResolutionDepth int NOT NULL,
    FlashMajor int NOT NULL,
    FlashMinor int NOT NULL,
    FlashMinor2 TEXT NOT NULL,
    NetMajor int NOT NULL,
    NetMinor int NOT NULL,
    UserAgentMajor int NOT NULL,
    UserAgentMinor VARCHAR(255) NOT NULL,
    CookieEnable int NOT NULL,
    JavascriptEnable int NOT NULL,
    IsMobile int NOT NULL,
    MobilePhone int NOT NULL,
    MobilePhoneModel TEXT NOT NULL,
    Params TEXT NOT NULL,
    IPNetworkID INTEGER NOT NULL,
    TraficSourceID int NOT NULL,
    SearchEngineID int NOT NULL,
    SearchPhrase TEXT NOT NULL,
    AdvEngineID int NOT NULL,
    IsArtifical int NOT NULL,
    WindowClientWidth int NOT NULL,
    WindowClientHeight int NOT NULL,
    ClientTimeZone int NOT NULL,
    ClientEventTime timestamptz NOT NULL,
    SilverlightVersion1 int NOT NULL,
    SilverlightVersion2 int NOT NULL,
    SilverlightVersion3 INTEGER NOT NULL,
    SilverlightVersion4 int NOT NULL,
    PageCharset TEXT NOT NULL,
    CodeVersion INTEGER NOT NULL,
    IsLink int NOT NULL,
    IsDownload int NOT NULL,
    IsNotBounce int NOT NULL,
    FUniqID BIGINT NOT NULL,
    OriginalURL TEXT NOT NULL,
    HID INTEGER NOT NULL,
    IsOldCounter int NOT NULL,
    IsEvent int NOT NULL,
    IsParameter int NOT NULL,
    DontCountHits int NOT NULL,
    WithHash int NOT NULL,
    HitColor CHAR NOT NULL,
    LocalEventTime timestamptz NOT NULL,
    Age int NOT NULL,
    Sex int NOT NULL,
    Income int NOT NULL,
    Interests int NOT NULL,
    Robotness int NOT NULL,
    RemoteIP INTEGER NOT NULL,
    WindowName INTEGER NOT NULL,
    OpenerName INTEGER NOT NULL,
    HistoryLength int NOT NULL,
    BrowserLanguage TEXT NOT NULL,
    BrowserCountry TEXT NOT NULL,
    SocialNetwork TEXT NOT NULL,
    SocialAction TEXT NOT NULL,
    HTTPError int NOT NULL,
    SendTiming INTEGER NOT NULL,
    DNSTiming INTEGER NOT NULL,
    ConnectTiming INTEGER NOT NULL,
    ResponseStartTiming INTEGER NOT NULL,
    ResponseEndTiming INTEGER NOT NULL,
    FetchTiming INTEGER NOT NULL,
    SocialSourceNetworkID int NOT NULL,
    SocialSourcePage TEXT NOT NULL,
    ParamPrice BIGINT NOT NULL,
    ParamOrderID TEXT NOT NULL,
    ParamCurrency TEXT NOT NULL,
    ParamCurrencyID int NOT NULL,
    OpenstatServiceName TEXT NOT NULL,
    OpenstatCampaignID TEXT NOT NULL,
    OpenstatAdID TEXT NOT NULL,
    OpenstatSourceID TEXT NOT NULL,
    UTMSource TEXT NOT NULL,
    UTMMedium TEXT NOT NULL,
    UTMCampaign TEXT NOT NULL,
    UTMContent TEXT NOT NULL,
    UTMTerm TEXT NOT NULL,
    FromTag TEXT NOT NULL,
    HasGCLID int NOT NULL,
    RefererHash BIGINT NOT NULL,
    URLHash BIGINT NOT NULL,
    CLID INTEGER NOT NULL,
    PRIMARY KEY (
        CounterID, 
        EventDate, 
        UserID, 
        EventTime, 
        WatchID
    )
) WITH (
    distribution_key='UserID',
    segment_key='EventTime',
    clustering_key='CounterID,EventDate,UserID,EventTime,WatchID',
    bitmap_columns='advengineid, counterid, isrefresh, isdownload, islink,refererhash,dontcounthits,urlhash'
);